services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_app
    user: "1000:1000" 
    volumes:
      - ./apps/api:/var/www/html
    depends_on:
      - postgres
      - redis
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "8085:80"            
    volumes:
      - ./apps/api:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: portafolio
      POSTGRES_USER: portafolio
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis_server
    ports:
      - "6379:6379"
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "8025:8025"   
      - "1025:1025"   
    networks:
      - laravel

  web:
    image: node:20-alpine
    container_name: web_vite
    working_dir: /app
    volumes:
      - ./apps/web:/app
    environment:
      VITE_API_BASE_URL: /api
      VITE_ASSETS_BASE_URL: http://127.0.0.1:8085
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    depends_on:
      - nginx
    networks:
      - laravel

volumes:
  postgres_data:

networks:
  laravel:
    driver: bridge

